### ISSUE TITLE
Multiple choice question - Store

### ISSUE THREAD

**Issue by sebasruii** [EGC-23-24/decide-part-lorca#120]

**Comment by sebasruii** [comment]
Next step is to configure the Store ( https://github.com/EGC-23-24/decide-part-lorca/issues/120 )module to properly process multiple choice questions. The options selected are encrypted separately and then joined in a single array that is sent as JSON as part of the POST payload to Store. An example of the JSON is provided:

{"votes":  [{"a":"80340721210858618718397228947692684208900141035522360189475935759932166140809","b":"101379022952357997333885496174865010508359748037310390188433859785959872031471"}, {"a":"51099967322316300124349566535819553952116348155662563108509013760151845742387","b":"99174952063096496787997938362417827123691510538928498669493845117384513592184"}], "voting":1, "voter":2, "token":"d686aae4681b7b5951b8ad315f972a6307da1905"}

**Comment by jmartinacu** [comment]
I can't do anything until the features multiple choice question and multiple questions voting are merged. And I have information about the final JSON payload store will receive.
