### ISSUE TITLE
Multiple Choice - Store

### ISSUE THREAD

**Issue by alblopnov** [EGC-23-24/decide-part-lorca#124]
While making a multiple choice voting, when you access the booth and try to vote you get a Error: Bad Request error. As you can see in the bottom right corner the error is asociated with the store module.

![Image](https://github.com/EGC-23-24/decide-part-lorca/assets/74500641/e3c71b51-dc1a-49ad-91e3-6856faa44a93)

**Comment by jmartinacu** [comment]
d
