### ISSUE TITLE
Error in comment voting tests - Voting

### ISSUE THREAD

**Issue by alvarobernal2412** [EGC-23-24/decide-part-lorca#170]
The GitHub action tests failed to merge PR #152 due to errors in the test called test_complete_voting, I suggest opening a new branch from the epic to solve this incident and then reopen the PR.

![Image](https://github.com/EGC-23-24/decide-part-lorca/assets/80347035/11f64086-fc2f-46e1-bb63-23b4b6f85899)

**Comment by alvarobernal2412** [comment]
A new feature has been added to the CI, , allowing it to be restarted using the label **_ready_**

**Comment by josgarber6** [comment]
The error has been solved in the pull request #178
