### ISSUE TITLE
Error in multiple options voting tests - Voting

### ISSUE THREAD

**Issue by alvarobernal2412** [EGC-23-24/decide-part-lorca#173]
The GitHub action tests failed to merge PR #171  due to errors in some voting tests, I suggest opening a new branch from the epic to solve this incident and then open a new PR. 

![Image](https://github.com/EGC-23-24/decide-part-lorca/assets/80347035/985111fa-7e38-43bd-8c4b-b0e733ec009c)

**Comment by sebasruii** [comment]
This incidence has been resolved in PR #184
