### ISSUE TITLE
Wrong data processing in preference voting - Voting

### ISSUE THREAD

**Issue by alvarobernal2412** [EGC-23-24/decide-part-lorca#215]
Once you have voted for a preference, the votes are calculated incorrectly. In my example, I have ranked Instagram first, then Twitter and then Facebook, but Facebook is shown as the winner.

![Image](https://github.com/EGC-23-24/decide-part-lorca/assets/80347035/e2e3c88b-e93a-46c0-ab6a-ebc39165920e)

**Comment by JuanAntonioJimenezdelVillar** [comment]
Solved in #216
