### ISSUE TITLE
Error in preference voting - Visualizer

### ISSUE THREAD

**Issue by JuanAntonioJimenezdelVillar** [EGC-23-24/decide-part-lorca#217]
Due to changes in preference postprocess logic, some charts are not displaying correctly voting information.

![Image](https://github.com/EGC-23-24/decide-part-lorca/assets/73228070/5e7fe461-044a-49d1-9e3f-70c51d32ef6d)

**Comment by alejandromd** [comment]
After the correction in the postprocessing one of the graphs did not show the information correctly, after these changes all the graphs of the visualizer work correctly.
```
http://localhost:8000/visualizer/[votingID]/
``` 
This incident is resolved in the PR #219
