### ISSUE TITLE
Correct the translation of the application in the import/export census - Census

### ISSUE THREAD

**Issue by alejandromd** [EGC-23-24/decide-part-lorca#225]
The application must be in English, in the section on:
```
http://127.0.0.1:8000/census/import/
``` 
There is content in Spanish, I show you the error:

![Image](https://github.com/EGC-23-24/decide-part-lorca/assets/72470942/5ccccb12-ec13-448f-ab53-9db564dcef24)

**Comment by alvgonfri** [comment]
Solved in #300
