### ISSUE TITLE
Multiple question - Visualizer

### ISSUE THREAD

**Issue by alvarobernal2412** [EGC-23-24/decide-part-lorca#325]
We need a visualizer view that supports other types of voting, in particular multiple-question voting.

**Comment by alejandromd** [comment]
This functionality was worked on and implemented until the different modules related to voting were working correctly, but due to time constraints it was decided at group level not to implement multiple questions in order to finish the project on time.

**Comment by alejandromd** [comment]
This functionality was worked on and implemented until the different modules related to voting were working correctly, but due to time constraints it was decided at group level not to implement multiple questions in order to finish the project on time.
