### ISSUE TITLE
Problem with maxoption - Booth

### ISSUE THREAD

**Issue by alblopnov** [EGC-23-24/decide-part-lorca#334]

**Comment by alblopnov** [comment]
When trying to access the booth, it fails due to the fact that the variable macOption does not have a value

![Image](https://github.com/EGC-23-24/decide-part-lorca/assets/74500641/008a32bc-ac3c-404b-b399-3ca75d3ca250)

**Comment by sebasruii** [comment]
This has been resolved in the linked PR.
