### ISSUE TITLE
Multiple Questions - Store

### ISSUE THREAD

**Issue by sebasruii** [EGC-23-24/decide-part-lorca#59]

**Comment by goncammej** [comment]
The booth votes will be sent in json format following the example structure below:

```json
{
  "vote": [
    {
      "a": "5712355842337148670080350028897151693675874309289339778246854865386297097306",
      "b": "30166565991825993911550749740875524569294925550045341205679968676448529434050"
    },
    {
      "a": "23227573364589331308259612975189546608550597217908563661052582379801961503972",
      "b": "24326391118614201042739856283582506313039452079075109881443147448017969056677"
    },
    {
      "a": "62284755462212899919149396305138764281265861750836565794972689559455529582709",
      "b": "31685822213672521400269018729560904763883424486051598330000175973737373578101"
    }
  ],
  "voting": 1,
  "voter": 1,
  "token": "fc9dcafdff1490483effb1f9a762f88f6c91f8d4"
}
```

The objects within the vote array are ordered in the same order in which the questions are passed to the booth. Each pair a, b within the array represents the encrypted answer to each of the questions.

**Comment by jmartinacu** [comment]
I can't do anything until the features multiple choice question and multiple questions voting are merged. And I have information about the final JSON payload store will receive.

**Comment by alvarobernal2412** [comment]
This issue will be closed as unplanned as this functionality will not be realised. In addition, the creator should have added a description explaining what had to be done to resolve the issue.
