### ISSUE TITLE
Team diary - Doc

### ISSUE THREAD

**Issue by alvarobernal2412** [EGC-23-24/decide-part-lorca#90]

**Comment by alejandromd** [comment]
In the team diary you can see all important team decisions. It contains the minutes of meetings and important decisions that were made.
In addition to saying when important decisions were made, add what times and tasks were decided and what actual time allocation was made for each of the team members. team members.
This document can be found in the project path: _/doc/diario-de-equipo.md_

**Comment by Thealean28** [comment]
This incident is resolved in the pull request: #318
