### ISSUE TITLE
Create Yes/No Voting - Voting

### ISSUE THREAD

**Issue by JuanAntonioJimenezdelVillar** [EGC-23-24/decide-part-lorca#96]
I tried to create a vote with the options yes/no and in the voting process, I get an error in the console that does not let me register the vote.

Below is a screenshot of the error that appears:

![Image](https://github.com/EGC-23-24/decide-part-lorca/assets/73228070/90a9ac60-7c8b-4ec0-8ce3-d60935818215)

**Comment by JuanAntonioJimenezdelVillar** [comment]
The process I have followed to get the error is as follows:

1.  I enter in the admin section logged as admin .
2. Create basic user.
3. Create a question with its relevant fields and selecting yes/no question field.
4. Create yes/no options for that question. Select number 1 and in option add "si". The same with the "no" corresponding question(number 2 and "no" as option).
5. Create auth for http://localhost:8000.
6. Create voting with the yes/no question.
7. Create census with voting id: {votingId} and voter id: {voterId} in this case, 1 and 2 accordingly.
8. Start voting.
9. Enter in booth/{votingId}
10. Select the Si box.
And then it gets the error I mentioned.

**Comment by alvarobernal2412** [comment]
Please, I need more information to give you some feedback. It would be nice if you can tell me how you create the voting step by step

**Comment by JuanAntonioJimenezdelVillar** [comment]
Okey. I´LL try that.

**Comment by JuanAntonioJimenezdelVillar** [comment]
The issue was about what you said. Now I can vote.
Thank you very much.
